# Generated by Django 2.1.7 on 2019-02-27 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190227_0226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_id',
            new_name='menu_item_id',
        ),
    ]
